CREATE OR REPLACE PACKAGE PKG_PROFESSOR AS
    CURSOR C_TURMAS_PROFESSOR RETURN PROFESSORES%ROWTYPE;
    FUNCTION TOTAL_TURMAS_PROFESSOR(p_id_professor IN NUMBER) RETURN NUMBER;
    FUNCTION PROFESSOR_DISCIPLINA(p_id_disciplina IN NUMBER) RETURN VARCHAR2;
END PKG_PROFESSOR;
/

CREATE OR REPLACE PACKAGE BODY PKG_PROFESSOR AS
    CURSOR C_TURMAS_PROFESSOR IS
        SELECT P.NOME, COUNT(T.ID) AS TOTAL_TURMAS
        FROM PROFESSORES P
        JOIN TURMAS T ON P.ID = T.ID_PROFESSOR
        GROUP BY P.NOME
        HAVING COUNT(T.ID) > 1;

    FUNCTION TOTAL_TURMAS_PROFESSOR(p_id_professor IN NUMBER) RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_total
        FROM TURMAS
        WHERE ID_PROFESSOR = p_id_professor;
        RETURN v_total;
    END;

    FUNCTION PROFESSOR_DISCIPLINA(p_id_disciplina IN NUMBER) RETURN VARCHAR2 IS
        v_nome_professor VARCHAR2(100);
    BEGIN
        SELECT P.NOME
        INTO v_nome_professor
        FROM PROFESSORES P
        JOIN DISCIPLINAS D ON P.ID = D.ID_PROFESSOR
        WHERE D.ID = p_id_disciplina;
        RETURN v_nome_professor;
    END;
END PKG_PROFESSOR;
/
