CREATE OR REPLACE PACKAGE PKG_ALUNO AS
    PROCEDURE EXCLUIR_ALUNO(p_id_aluno IN NUMBER);
    CURSOR C_ALUNOS_MAIORES_18 RETURN ALUNOS%ROWTYPE;
    CURSOR C_ALUNOS_POR_CURSO(p_id_curso IN NUMBER) RETURN ALUNOS%ROWTYPE;
END PKG_ALUNO;
/

CREATE OR REPLACE PACKAGE BODY PKG_ALUNO AS
    PROCEDURE EXCLUIR_ALUNO(p_id_aluno IN NUMBER) IS
    BEGIN
        DELETE FROM MATRICULAS WHERE ID_ALUNO = p_id_aluno;
        DELETE FROM ALUNOS WHERE ID = p_id_aluno;
    END;

    CURSOR C_ALUNOS_MAIORES_18 IS
        SELECT NOME, DATA_NASCIMENTO
        FROM ALUNOS
        WHERE TRUNC(MONTHS_BETWEEN(SYSDATE, DATA_NASCIMENTO) / 12) > 18;

    CURSOR C_ALUNOS_POR_CURSO(p_id_curso IN NUMBER) IS
        SELECT A.NOME
        FROM ALUNOS A
        JOIN MATRICULAS M ON A.ID = M.ID_ALUNO
        WHERE M.ID_CURSO = p_id_curso;
END PKG_ALUNO;
/
