CREATE OR REPLACE PACKAGE PKG_DISCIPLINA AS
    PROCEDURE CADASTRAR_DISCIPLINA(p_nome IN VARCHAR2, p_descricao IN VARCHAR2, p_carga_horaria IN NUMBER);
    CURSOR C_ALUNOS_POR_DISCIPLINA RETURN DISCIPLINAS%ROWTYPE;
    CURSOR C_MEDIA_IDADE_DISCIPLINA(p_id_disciplina IN NUMBER) RETURN DISCIPLINAS%ROWTYPE;
    PROCEDURE LISTAR_ALUNOS_DISCIPLINA(p_id_disciplina IN NUMBER);
END PKG_DISCIPLINA;
/

CREATE OR REPLACE PACKAGE BODY PKG_DISCIPLINA AS
    PROCEDURE CADASTRAR_DISCIPLINA(p_nome IN VARCHAR2, p_descricao IN VARCHAR2, p_carga_horaria IN NUMBER) IS
    BEGIN
        INSERT INTO DISCIPLINAS (NOME, DESCRICAO, CARGA_HORARIA)
        VALUES (p_nome, p_descricao, p_carga_horaria);
    END;

    CURSOR C_ALUNOS_POR_DISCIPLINA IS
        SELECT D.NOME, COUNT(M.ID_ALUNO) AS TOTAL_ALUNOS
        FROM DISCIPLINAS D
        JOIN MATRICULAS M ON D.ID = M.ID_DISCIPLINA
        GROUP BY D.NOME
        HAVING COUNT(M.ID_ALUNO) > 10;

    CURSOR C_MEDIA_IDADE_DISCIPLINA(p_id_disciplina IN NUMBER) IS
        SELECT AVG(TRUNC(MONTHS_BETWEEN(SYSDATE, A.DATA_NASCIMENTO) / 12)) AS MEDIA_IDADE
        FROM ALUNOS A
        JOIN MATRICULAS M ON A.ID = M.ID_ALUNO
        WHERE M.ID_DISCIPLINA = p_id_disciplina;

    PROCEDURE LISTAR_ALUNOS_DISCIPLINA(p_id_disciplina IN NUMBER) IS
    BEGIN
        FOR R IN (SELECT A.NOME
                  FROM ALUNOS A
                  JOIN MATRICULAS M ON A.ID = M.ID_ALUNO
                  WHERE M.ID_DISCIPLINA = p_id_disciplina) LOOP
            DBMS_OUTPUT.PUT_LINE('Aluno: ' || R.NOME);
        END LOOP;
    END;
END PKG_DISCIPLINA;
/
